(() => {
 const core=window.ParallelCareerCore,base=new URL('.',document.currentScript.src),storageKey='parallel-career-v3';
 let db;try{db=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{db={};}db.careers??={};db.names??={};
 const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(db));}catch{}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={three:'三分射手',mid:'中距离',finish:'终结',dunk:'扣篮',handle:'控球',pass:'组织',perimeter:'外线防守',interior:'内线防守',block:'封盖',rebound:'篮板磁铁',athletic:'运动能力',strength:'力量',creator:'持球创造',sniper:'狙击手',driver:'突破手','two-way':'攻防一体','three-d':'3D',air:'空中作业',hub:'组织中枢',paint:'油漆区霸主',weakness:'补齐短板','home-away':'主客场','postseason':'季后赛之星',wildcard:'百变',endurance:'耐力',ageless:'长青',borrow:'借来的一生',reaper:'收割者',apprentice:'名师速成'};
 const statNames={pts:'得分',reb:'篮板',ast:'助攻',stl:'抢断',blk:'盖帽'};
 let current,host,hooks,queued=false,originalAchievement=false;
 const recordsPromise=fetch(new URL('records.json',base)).then(r=>r.json());
 function name(H=current){const c=H?.career||H?.standardCareerSlot?.career;return c?.customName||db.names[c?.careerId]||H?.parallelDraftName||db.draftName||'我的球员';}
 function importCareer(c){if(!c?.careerId)return;core.migrate(c);const item=db.careers[c.careerId]??={name:c.customName||db.names[c.careerId]||'我的球员',seasons:{}};item.name=c.customName||db.names[c.careerId]||item.name;for(const s of c.seasons||[]){if(s.parallelStats)item.seasons[s.season]={...s.parallelStats,complete:true};else if(!item.seasons[s.season]){const convert=t=>Object.fromEntries(Object.entries({pts:'points',reb:'rebounds',ast:'assists',stl:'steals',blk:'blocks',three_m:'threes'}).map(([k,v])=>[k,Number(t?.[v])||0]));item.seasons[s.season]={season:s.season,regular:{games:s.playerAverages?.games||0,totals:convert(s.totals),highs:convert(s.singleGameHighs),counts:{},legacy:true},playoffs:{games:0,totals:convert(s.playoffTotals),highs:{},counts:{},legacy:true}};}}}
 function settle(result,career){if(!career)return;core.remember(career,career.seasonAugment);career.customName??=name();importCareer(career);career.reaperOpportunities??=[];for(const op of result.permanent_opportunities||[]){if(!career.reaperOpportunities.some(x=>x.key===op.key&&x.season===result.season))career.reaperOpportunities.push({...op,season:result.season});}const stats=result.parallel_stats||core.resultStats(result);db.careers[career.careerId].seasons[result.season]={...stats,complete:true};save();}
 function observe(){if(!current)return;for(const c of [current.career,current.standardCareerSlot?.career,current.trinityCareerSlot?.career])importCareer(c);const r=current.result,id=current.career?.careerId||current.activeRun?.request?.career_context?.career_id;if(!r||!id)return;const item=db.careers[id]??={name:name(),seasons:{}};if(item.seasons[r.season]?.complete)return;
  let count=current.regularSimulation?.currentGames||0;const moment=hooks?.moment?.();if(moment?.kind==='journey-result'||current.screen==='result'){item.seasons[r.season]={...(r.parallel_stats||core.resultStats(r)),complete:true};save();return;}
  // Regular-season live progress is counted only through already displayed games.
  if(moment?.kind==='season-checkpoint')count=Math.max(count,moment.checkpoint.games||0);
  const step=current.broadcastStep||0,played=[],moments=hooks?.moments?.()||[];for(let i=0;i<=step;i++){const m=moments[i];if(m?.kind==='game-box'&&m.game?.player_line&&!played.includes(m.game))played.push(m.game);}
  if(played.length)count=r.regular_season.games.length;
  if(count||played.length){item.seasons[r.season]={season:r.season,regular:core.summarize(r.regular_season.games.slice(0,count)),playoffs:core.summarize(played)};save();}
 }
 function scanSaved(){for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('colorbox-activity:'))continue;try{const visit=(v,depth=0)=>{if(!v||typeof v!=='object'||depth>12)return;if(v.careerId&&Array.isArray(v.seasons)){importCareer(v);return;}for(const child of Object.values(v))visit(child,depth+1);};visit(JSON.parse(localStorage.getItem(key)));}catch{}}save();}
 function dialog(title,body){const d=document.createElement('dialog');d.className='parallel-extra-dialog';d.innerHTML=`<header><h2>${esc(title)}</h2><button type="button" data-close aria-label="关闭">×</button></header>${body}`;d.querySelector('[data-close]').onclick=()=>{d.close();d.remove();};d.addEventListener('cancel',()=>d.remove());document.body.append(d);d.showModal();return d;}
 function rename(){const d=dialog('自建球员姓名',`<form><label>球员姓名<input name="playerName" maxlength="20" value="${esc(name())}" autocomplete="off" required></label><p>姓名保存在这份生涯中，可随时修改。</p><button type="submit">保存姓名</button></form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();const value=new FormData(e.target).get('playerName').trim().replace(/[\u0000-\u001f]/g,'').slice(0,20);if(!value)return;db.draftName=value;current.parallelDraftName=value;const c=current.career||current.standardCareerSlot?.career;if(c){c.customName=value;db.names[c.careerId]=value;importCareer(c);}save();await hooks.save();hooks.redraw();d.close();d.remove();};}
 function render(){queued=false;if(!host?.isConnected||!current)return;core.migrate(current.career);window.parallelRepairResult?.(current.result);repairOffers();if(current.career&&['active-season','development','offseason','contracts'].includes(current.career.phase))current.team=current.career.currentTeam;observe();if(!host.querySelector('[data-parallel-tools]')){const tools=document.createElement('div');tools.dataset.parallelTools='';tools.className='parallel-career-tools';tools.innerHTML=`<button type="button" data-parallel-name>姓名：${esc(name())} · 修改</button><button type="button" data-parallel-stats>统计与成就</button>`;tools.querySelector('[data-parallel-name]').onclick=rename;tools.querySelector('[data-parallel-stats]').onclick=showStats;host.prepend(tools);}
  const c=current.career||current.standardCareerSlot?.career;if(c?.permanentAugments?.length&&!host.querySelector('[data-permanent-augments]')){const box=document.createElement('details');box.dataset.permanentAugments='';box.className='parallel-permanent';box.innerHTML=`<summary>永久海克斯 · 已获得 ${c.permanentAugments.length} 张</summary><p>全部在后续赛季同时生效；条件型效果按对应场景触发。</p>${c.permanentAugments.map(a=>`<div>${esc(names[a.id]||a.id)} · ${a.tier}阶 <small>${esc(a.acquiredSeason||'旧存档迁移')}</small></div>`).join('')}`;host.querySelector('[data-parallel-tools]').after(box);}
  renderReaper(c);
  for(const p of host.querySelectorAll('.career-hex-summary small,.career-hex-sheet p,.career-hex-confirm')){if(p.textContent.includes('本季'))p.textContent=p.textContent.replaceAll('本季','全生涯');}
 }

 const repairs=new WeakSet();
 async function repairOffers(){const c=current?.career;if(!c?.pendingOffers?.length||repairs.has(c))return;const offers=c.pendingOffers,missing=offers.some(o=>!o.roster?.length||!o.title_odds),noStay=!offers.some(o=>o.kind==='stay'&&core.franchise(o.team)===core.franchise(c.currentTeam));if(!missing&&!noStay)return;repairs.add(c);try{if(noStay){const fresh=await window.parallelRequest('/career/offers',{data:{season:c.currentSeason,team:c.currentTeam,seed:current.seed,player:{overall:75}}});c.pendingOffers=fresh.offers;}else for(const o of offers){o.roster=await window.parallelRequest('/team-roster',{data:{season:parseInt(c.currentSeason)+1,team:o.team}}).then(x=>x.roster);o.title_odds??='季后赛竞争者';}await hooks.save();hooks.redraw();}catch{repairs.delete(c);}}
 function renderReaper(c){if(!c?.reaperOpportunities?.length||host.querySelector('[data-reaper-permanent]'))return;const pending=c.reaperOpportunities.filter(x=>!x.claimed&&x.options.some(id=>!c.rewards?.signatureSkills?.some(s=>s.id===id)));if(!pending.length)return;const box=document.createElement('section');box.dataset.reaperPermanent='';box.className='parallel-permanent';box.innerHTML='<strong>永久收割者 · 领取衣钵</strong><p>每张收割者在赢下一轮的赛季可领取一次；选择后永久保存。</p>';for(const op of pending){const label=document.createElement('p');label.textContent=op.season;box.append(label);for(const skill of op.skills.filter(s=>op.options.includes(s.id)&&!c.rewards?.signatureSkills?.some(x=>x.id===s.id))){const b=document.createElement('button');b.textContent=skill.mentor+' · '+skill.name;b.onclick=async()=>{b.disabled=true;hooks.grantSkill(c,skill.id,'reaper');op.claimed=skill.id;await hooks.save();hooks.redraw();};box.append(b);}}host.querySelector('[data-parallel-tools]').after(box);}
 function bind(G,H,ops){current=H;host=G;hooks=ops;core.migrate(H.career);if(H.career?.customName)db.names[H.career.careerId]=H.career.customName;if(!queued){queued=true;queueMicrotask(render);}}
 function prepare(path,data){if(!data)return data;if(path==='/simulate')return core.request(data,current?.career,name());if(path==='/career/develop')return {...data,permanent_augments:current?.career?.permanentAugments||[]};return data;}
 function summary(season){return {parallelStats:season.parallel_stats||core.resultStats(season),parallelAugments:season.permanent_augments||[]};}
 async function showStats(){observe();scanSaved();const records=await recordsPromise;const ids=Object.keys(db.careers),selectedId=current?.career?.careerId||ids.at(-1)||'',d=dialog('生涯统计与成就',`<label>选择生涯<select data-career>${ids.map(id=>`<option value="${esc(id)}" ${id===selectedId?'selected':''}>${esc(db.careers[id].name)} · ${Object.keys(db.careers[id].seasons).length}季</option>`).join('')}</select></label><label>统计范围<select data-scope><option value="regular">常规赛</option><option value="playoffs">季后赛</option></select></label><p>NBA 纪录核对：${records.verified}。历史参照仅比较常规赛，追平与超越分别标记。</p><main data-stats></main><button type="button" data-original>查看原有生涯成就</button>`);
  const draw=()=>{const scope=d.querySelector('[data-scope]').value,c=db.careers[d.querySelector('[data-career]').value],seasons=Object.values(c?.seasons||{}),totals={},highs={},counts={};let games=0,legacy=false;for(const s of seasons){const a=s[scope];if(!a)continue;games+=a.games||0;legacy||=a.legacy;for(const [k,v]of Object.entries(a.totals||{}))totals[k]=(totals[k]||0)+v;for(const [k,v]of Object.entries(a.highs||{}))highs[k]=Math.max(highs[k]||0,v);for(const [k,v]of Object.entries(a.counts||{}))counts[k]=(counts[k]||0)+v;}
   const card=(r,value)=>`<article class="parallel-record ${scope==='regular'&&value>=r.target?'unlocked':''}"><b>${esc(r.label)}</b><strong>${value||0} ${scope==='regular'?`/ ${r.target}`:''}</strong><small>${scope==='regular'?(value>r.target?'已超越历史纪录':value===r.target?'已追平历史纪录':`历史参照：${esc(r.holder)}`):'季后赛个人统计 · 不与常规赛纪录混算'}</small>${scope==='regular'?`<a href="${esc(r.source)}" target="_blank" rel="noopener">纪录来源</a>`:''}</article>`;
   const milestones=[['doubleDouble','两双'],['tripleDouble','三双'],['quadrupleDouble','四双'],['quintupleDouble','五双'],['fiveByFive','五乘五']];d.querySelector('[data-stats]').innerHTML=`<p>已统计 ${games} 场 · ${seasons.length} 季</p>${legacy?'<p>旧赛季已恢复基础总量和单场最高；未保存的多双明细无法追溯，之后按实际比赛计数。</p>':''}<h3>单场数据王</h3>${records.single.map(r=>card(r,highs[r.key])).join('')}<h3>累计数据王</h3>${records.career.map(r=>card(r,totals[r.key]??counts[r.key])).join('')}<h3>特殊表现</h3>${milestones.map(([k,label])=>`<article class="parallel-record ${(counts[k]||0)>0?'unlocked':''}"><b>${label}</b><strong>${counts[k]||0} 次</strong><small>${k==='quintupleDouble'?'原创极限挑战：五项基础数据同场均达到10':k==='fiveByFive'?'五项基础数据同场均达到5':'按同一场比赛达到两位数的项目统计，高阶多双同时计入低阶'}</small></article>`).join('')}`;};
  d.querySelector('[data-career]').onchange=draw;d.querySelector('[data-scope]').onchange=draw;draw();d.querySelector('[data-original]').onclick=()=>{d.close();d.remove();const button=document.querySelector('[data-action="open-achievements"]');if(button){originalAchievement=true;button.click();originalAchievement=false;}else hooks?.redraw();};
 }
 document.addEventListener('click',e=>{const b=e.target.closest?.('[data-action="open-achievements"]');if(b&&!originalAchievement){e.preventDefault();e.stopImmediatePropagation();showStats();}},true);
 const style=document.createElement('style');style.textContent='.parallel-career-tools{display:flex;gap:8px;padding:10px;justify-content:center;flex-wrap:wrap}.parallel-career-tools button{border:1px solid #d4cbb9;background:#faf7ef;color:#203e39;border-radius:8px;padding:8px 12px;font:inherit;font-size:12px}.parallel-permanent{margin:0 12px 12px;padding:12px;border:1px solid #cab884;border-radius:10px;background:#f6f0dd;color:#283b32}.parallel-permanent div{padding:6px;border-top:1px solid #ddd}.parallel-extra-dialog{box-sizing:border-box;width:min(94vw,520px);max-height:90dvh;border:1px solid #c4b588;border-radius:16px;background:#faf7ef;color:#203e39;padding:20px;font-family:inherit;overflow:auto}.parallel-extra-dialog::backdrop{background:#0009}.parallel-extra-dialog header{display:flex;align-items:center;justify-content:space-between;gap:12px}.parallel-extra-dialog h2{font-size:22px}.parallel-extra-dialog button,.parallel-extra-dialog select,.parallel-extra-dialog input{font:inherit;padding:10px;border:1px solid #bbb49f;border-radius:8px;background:#fff;color:#203e39}.parallel-extra-dialog label{display:grid;gap:8px;margin:12px 0}.parallel-extra-dialog p,.parallel-record small{font-size:12px;line-height:1.7}.parallel-record{display:grid;grid-template-columns:1fr auto;gap:6px;padding:14px;margin:10px 0;border:1px solid #d5cdbb;border-radius:10px;background:#fff}.parallel-record small{grid-column:1/-1}.parallel-record a{font-size:11px;color:#55776a}.parallel-record.unlocked{border-color:#b49436;background:#fff6ce}';document.head.append(style);
 window.parallelCareer={bind,name,prepare,summary,settle,remember:core.remember,showStats,attach:career=>{career.customName??=name();core.remember(career,career.seasonAugment);}};
})();
