(() => {
 const core=window.ParallelCareerCore,base=new URL('.',document.currentScript.src),storageKey='parallel-career-v3';
 let db;try{db=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{db={};}db.careers??={};db.names??={};
 const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(db));}catch{}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={three:'三分射手',mid:'中距离',finish:'终结',dunk:'扣篮',handle:'控球',pass:'组织',perimeter:'外线防守',interior:'内线防守',block:'封盖',rebound:'篮板磁铁',athletic:'运动能力',strength:'力量',creator:'持球创造',sniper:'狙击手',driver:'突破手','two-way':'攻防一体','three-d':'3D',air:'空中作业',hub:'组织中枢',paint:'油漆区霸主',weakness:'补齐短板','home-away':'主客场','postseason':'季后赛之星',wildcard:'百变',endurance:'耐力',ageless:'长青',borrow:'借来的一生',reaper:'收割者',apprentice:'名师速成'};
 const statNames={pts:'得分',reb:'篮板',ast:'助攻',stl:'抢断',blk:'盖帽'};
 let current,host,hooks,queued=false,originalAchievement=false;
 const recordsPromise=fetch(new URL('records.json'+new URL(document.currentScript.src).search,base)).then(r=>r.json());
 function name(H=current){const c=H?.career||H?.standardCareerSlot?.career;return c?.customName||db.names[c?.careerId]||H?.parallelDraftName||db.draftName||'我的球员';}
 function importCareer(c,result){if(!c?.careerId)return;core.migrate(c);const item=db.careers[c.careerId]??={name:c.customName||db.names[c.careerId]||'我的球员',seasons:{}};item.name=c.customName||db.names[c.careerId]||item.name;for(const season of c.seasons||[]){const old=item.seasons[season.season];if(result?.season===season.season){item.seasons[season.season]={...core.resultStats(result),complete:true};continue;}if(old?.stats_version>=2&&!season.parallelStats?.stats_version)continue;item.seasons[season.season]={...core.archivedStats(season),complete:true};}}
 function settle(result,career){if(!career)return;core.remember(career,career.seasonAugment);career.customName??=name();importCareer(career);core.collectReaper(career,result,{complete:true});const stats=result.parallel_stats||core.resultStats(result);db.careers[career.careerId].seasons[result.season]={...stats,complete:true};save();}
 function observe(){if(!current)return;for(const c of [current.career,current.standardCareerSlot?.career,current.trinityCareerSlot?.career])importCareer(c,c===current.career?current.result:null);const r=current.result,id=current.career?.careerId||current.activeRun?.request?.career_context?.career_id;if(!r||!id)return;if(core.collectReaper(current.career,r,{moments:hooks?.moments?.()||[],step:current.broadcastStep||0,complete:hooks?.moment?.()?.kind==='journey-result'}))hooks.save().catch(()=>{});const item=db.careers[id]??={name:name(),seasons:{}};if(item.seasons[r.season]?.complete&&item.seasons[r.season]?.stats_version>=2)return;
  const moment=hooks?.moment?.();const complete=moment?.kind==='journey-result';
  item.seasons[r.season]={...core.visibleStats(r,{regularGames:current.regularSimulation?.currentGames||0,moments:hooks?.moments?.()||[],step:current.broadcastStep||0,complete}),complete};save();
 }
 function scanSaved(){for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('colorbox-activity:'))continue;try{const visit=(v,depth=0)=>{if(!v||typeof v!=='object'||depth>12)return;if(v.career&&v.result)importCareer(v.career,v.result);if(v.careerId&&Array.isArray(v.seasons)){importCareer(v);return;}for(const child of Object.values(v))visit(child,depth+1);};visit(JSON.parse(localStorage.getItem(key)));}catch{}}save();}
 function dialog(title,body){const d=document.createElement('dialog');d.className='parallel-extra-dialog';d.innerHTML=`<header><h2>${esc(title)}</h2><button type="button" data-close aria-label="关闭">×</button></header>${body}`;d.querySelector('[data-close]').onclick=()=>{d.close();d.remove();};d.addEventListener('cancel',()=>d.remove());document.body.append(d);d.showModal();return d;}
 function rename(){const d=dialog('自建球员姓名',`<form><label>球员姓名<input name="playerName" maxlength="20" value="${esc(name())}" autocomplete="off" required></label><p>姓名保存在这份生涯中，可随时修改。</p><button type="submit">保存姓名</button></form>`);d.querySelector('form').onsubmit=async e=>{e.preventDefault();const value=new FormData(e.target).get('playerName').trim().replace(/[\u0000-\u001f]/g,'').slice(0,20);if(!value)return;db.draftName=value;current.parallelDraftName=value;const c=current.career||current.standardCareerSlot?.career;if(c){c.customName=value;db.names[c.careerId]=value;importCareer(c);}save();await hooks.save();hooks.redraw();d.close();d.remove();};}
 function render(){queued=false;if(!host?.isConnected||!current)return;core.migrate(current.career);window.parallelRepairResult?.(current.result);repairReaper();repairOffers();repairDraft();if(current.career&&['active-season','development','offseason','contracts'].includes(current.career.phase))current.team=current.career.currentTeam;observe();if(!host.querySelector('[data-parallel-tools]')){const tools=document.createElement('div');tools.dataset.parallelTools='';tools.className='parallel-career-tools';tools.innerHTML=`<button type="button" data-parallel-name>姓名：${esc(name())} · 修改</button><button type="button" data-parallel-stats>成就</button>`;tools.querySelector('[data-parallel-name]').onclick=rename;tools.querySelector('[data-parallel-stats]').onclick=showStats;host.prepend(tools);}
  const c=current.career||current.standardCareerSlot?.career;if(c?.permanentAugments?.length&&!host.querySelector('[data-permanent-augments]')){const box=document.createElement('details');box.dataset.permanentAugments='';box.className='parallel-permanent';box.innerHTML=`<summary>永久海克斯 · 已获得 ${c.permanentAugments.length} 张</summary><p>全部在后续赛季同时生效；条件型效果按对应场景触发。</p>${c.permanentAugments.map(a=>`<div>${esc(names[a.id]||a.id)} · ${a.tier}阶 <small>${esc(a.acquiredSeason||'旧存档迁移')}</small></div>`).join('')}`;host.querySelector('[data-parallel-tools]').after(box);}
  renderReaper(c);
  const walker=document.createTreeWalker(host,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const text=walker.currentNode;let value=text.nodeValue.replaceAll('all-time赛季','队史巅峰').replaceAll('all-time','队史巅峰').replaceAll('借用一项传奇衣钵度过本季','永久借用一项传奇衣钵，多张卡可累积').replaceAll('本赛季生效','全生涯生效 · 可累积').replaceAll('选择本季天赋','选择永久天赋').replaceAll('选一项，带入新赛季','选一项，永久累积到生涯').replaceAll('每季选一项天赋，打出不同的生涯。','每季新增一项永久天赋，多张效果累积。');if(value!==text.nodeValue)text.nodeValue=value;}
 }

 const reaperRepairs=new WeakSet();
 function repairReaper(){const r=current?.result,c=current?.career;if(!r||!c?.permanentAugments?.some(a=>a.id==='reaper')||r.reaper_rounds||reaperRepairs.has(r))return;reaperRepairs.add(r);window.parallelRepairReaper(r).then(()=>{observe();hooks.save().catch(()=>{});hooks.redraw();}).catch(()=>reaperRepairs.delete(r));}
 let draftRepairing=false;
 async function repairDraft(){if(draftRepairing||current?.loading||!current?.offers?.length||current.parallelDraftFixedVersion==='r12'||Object.keys(current.donors||{}).length>=13)return;draftRepairing=true;const H=current;try{const round=Object.keys(H.donors||{}).length;if((round+1)%4===0&&H.draftSeason!=='all-time'){const fresh=await wait(window.parallelRequest('/team-offers',{data:{...H.draftOfferSession,round,lockedTeam:H.draftTeam,seed:H.seed}}));H.offers=fresh.candidates;H.draftSeason=fresh.season;H.draftTeam=fresh.team;H.draftTeamId=fresh.team_id;H.expandedCandidateId=null;}else H.offers=await window.parallelRefreshCandidates(H.offers);H.parallelDraftFixedVersion='r12';await hooks.save();hooks.redraw();}catch(e){H.error=e.message;H.parallelDraftFixedVersion='r12';hooks.redraw();}finally{draftRepairing=false;}}
 const repairs=new WeakSet();
 async function repairOffers(){const c=current?.career;if(!c?.pendingOffers?.length||repairs.has(c))return;const offers=c.pendingOffers,missing=offers.some(o=>!o.roster?.length||!o.title_odds),noStay=!offers.some(o=>o.kind==='stay'&&core.franchise(o.team)===core.franchise(c.currentTeam));if(!missing&&!noStay)return;repairs.add(c);try{if(noStay){const fresh=await window.parallelRequest('/career/offers',{data:{season:c.currentSeason,team:c.currentTeam,seed:current.seed,player:{overall:75}}});c.pendingOffers=fresh.offers;}else for(const o of offers){o.roster=await window.parallelRequest('/team-roster',{data:{season:parseInt(c.currentSeason)+1,team:o.team}}).then(x=>x.roster);o.title_odds??='季后赛竞争者';}await hooks.save();hooks.redraw();}catch{repairs.delete(c);}}
 function renderReaper(c){if(!c?.reaperOpportunities?.length||host.querySelector('[data-reaper-permanent]'))return;const pending=c.reaperOpportunities.filter(x=>!x.claimed&&x.options.some(id=>!c.rewards?.signatureSkills?.some(s=>s.id===id)));if(!pending.length)return;const box=document.createElement('section');box.dataset.reaperPermanent='';box.className='parallel-permanent';box.innerHTML='<strong>永久收割者 · 领取衣钵</strong><p>每张收割者每赛季可领取一次；淘汰传奇后立即解锁。多张卡分别领取不同衣钵，刷新不会重置。</p>';for(const op of pending){const label=document.createElement('p');label.textContent=op.season;box.append(label);for(const skill of op.skills.filter(s=>op.options.includes(s.id)&&!c.rewards?.signatureSkills?.some(x=>x.id===s.id))){const b=document.createElement('button');b.textContent=skill.mentor+' · '+skill.name;b.onclick=()=>{if(op.claimed||c.rewards?.signatureSkills?.some(x=>x.id===skill.id))return;b.disabled=true;hooks.grantSkill(c,skill.id,'reaper');if(!c.rewards?.signatureSkills?.some(x=>x.id===skill.id))return;op.claimed=skill.id;hooks.save().catch(()=>{});hooks.redraw();};box.append(b);}}host.querySelector('[data-parallel-tools]').after(box);}
 function bind(G,H,ops){current=H;host=G;hooks=ops;core.migrate(H.career);if(H.career?.customName)db.names[H.career.careerId]=H.career.customName;if(!queued){queued=true;queueMicrotask(render);}}
 function prepare(path,data){if(!data)return data;if(path==='/simulate')return core.request(data,current?.career,name());if(path==='/career/develop')return {...data,permanent_augments:current?.career?.permanentAugments||[]};return data;}
 function summary(season){return {parallelStats:season.parallel_stats||core.resultStats(season),parallelAugments:season.permanent_augments||[]};}
 let recordData;
 recordsPromise.then(r=>{recordData=r;mountRecords();}).catch(()=>{});
 function aggregate(id,scope){const totals={},highs={},counts={};let games=0,legacy=false;for(const s of Object.values(db.careers[id]?.seasons||{})){const a=s[scope];if(!a)continue;games+=a.games||0;legacy||=a.legacy;for(const[k,v]of Object.entries(a.totals||{}))totals[k]=(totals[k]||0)+v;for(const[k,v]of Object.entries(a.highs||{}))highs[k]=Math.max(highs[k]||0,v);for(const[k,v]of Object.entries(a.counts||{}))counts[k]=(counts[k]||0)+v;}return{totals,highs,counts,games,legacy};}
 function definitions(scope='regular'){if(!recordData)return[];const source=scope==='playoffs'?recordData.playoffs:recordData;if(!source)return[];return [...source.single.map(r=>({...r,id:scope+'-single-'+r.key,type:'single'})),...source.career.map(r=>({...r,id:scope+'-career-'+r.key,type:'career'})),...[['doubleDouble','两双'],['tripleDouble','三双'],['quadrupleDouble','四双'],['quintupleDouble','五双'],['fiveByFive','五乘五']].map(([key,label])=>({id:scope+'-special-'+key,key,label,target:1,type:'special'}))];}
 const value=(r,a)=>r.type==='single'?a.highs[r.key]||0:r.type==='special'?a.counts[r.key]||0:a.totals[r.key]??a.counts[r.key]??0;
 function mountRecords(){if(!recordData)return;const cabinets=document.querySelectorAll('.achievement-sheet,.prism-achievement-cabinet');for(const room of cabinets){if(room.querySelector('[data-native-records]'))continue;const panel=room.querySelector('[data-achievement-panel="legacy"]');if(!panel)continue;scanSaved();const ids=Object.keys(db.careers),allDefs=['regular','playoffs'].flatMap(scope=>definitions(scope).map(r=>({...r,scope}))),unlocked=allDefs.filter(r=>ids.some(id=>value(r,aggregate(id,r.scope))>=r.target)).length;
  const native=room.classList.contains('prism-achievement-cabinet'),box=document.createElement('details');box.open=true;box.dataset.nativeRecords='';box.className=native?'pac-pending':'legend-achievement-group';box.innerHTML=`<summary>数据纪录与多双 · ${unlocked}/${allDefs.length}</summary><div class="native-records-controls">${ids.length>1?`<label>生涯<select data-record-career>${ids.map(id=>`<option value="${esc(id)}">${esc(db.careers[id].name)}</option>`).join('')}</select></label>`:`<p>${esc(db.careers[ids[0]]?.name||'我的球员')}</p>`}<nav><button type="button" data-record-scope="regular" aria-pressed="true">常规赛</button><button type="button" data-record-scope="playoffs" aria-pressed="false">季后赛</button></nav></div><div data-record-content></div>`;(panel.querySelector('.achievement-section.achievement-panel')||panel).append(box);
  const chosen=current?.career?.careerId||ids.at(-1)||'',select=box.querySelector('select');if(select&&ids.includes(chosen))select.value=chosen;let scope='regular';const draw=()=>{observe();const a=aggregate(select?.value||chosen,scope),defs=definitions(scope);let html=`<p class="native-records-note">已统计 ${a.games} 场${a.legacy?'（旧档可能缺少场数）':''}。${scope==='regular'?'常规赛':'季后赛'}纪录独立判定，追平或超越即可点亮。参考快照：${esc(recordData.verified)}。</p>`;if(a.legacy)html+='<p class="native-records-note">旧档未保存的单场最高、多双明细标为未记录；已保存的累计数据保留，新增比赛实时计数。</p>';for(const[type,title]of [['single','单场数据王'],['career','累计数据王'],['special','特殊表现']]){html+=`<h4>${title}</h4><div class="${native?'pac-earned-list':'achievement-legacy-list'}">`;for(const r of defs.filter(r=>r.type===type)){const known=!a.legacy||Object.hasOwn(r.type==='single'?a.highs:r.type==='special'||r.key.includes('Double')?a.counts:a.totals,r.key),v=value(r,a),earned=known&&v>=r.target,progress=!known?'旧档未记录':r.type==='special'?`${v} 次`:`${v.toLocaleString('zh-CN')} / ${r.target.toLocaleString('zh-CN')}`,hint=r.type==='special'?r.key==='fiveByFive'?'五项基础数据同场均达到5':r.key==='quintupleDouble'?'五项基础数据同场均达到10':r.key==='quadrupleDouble'?'同场四项基础数据达到10':r.key==='tripleDouble'?'同场三项基础数据达到10':'同场两项基础数据达到10':`${earned?(v===r.target?'已追平':'已超越'):'历史参照'} · ${r.holder}`;html+=native?`<article class="${earned?'pac-earned':'pac-locked'}"><small>${earned?'已达成':'进行中'}</small><h4>${esc(r.label)}</h4><p>${progress}</p><p class="pac-story">${esc(hint)}</p>${r.source?`<a class="native-record-source" href="${esc(r.source)}" target="_blank" rel="noopener">纪录来源</a>`:''}</article>`:`<article class="achievement-legacy${earned?' is-unlocked':''}"><span>${earned?'✓':'◇'}</span><div><small>${earned?'生涯达成':'进行中'}</small><strong>${esc(r.label)}</strong><p>${progress}</p><em>${esc(hint)}</em>${r.source?`<a class="native-record-source" href="${esc(r.source)}" target="_blank" rel="noopener">纪录来源</a>`:''}</div></article>`;}html+='</div>';}box.querySelector('[data-record-content]').innerHTML=html;};
  box.querySelectorAll('[data-record-scope]').forEach(b=>b.onclick=()=>{scope=b.dataset.recordScope;box.querySelectorAll('[data-record-scope]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();});if(select)select.onchange=draw;draw();
  const tab=room.querySelector('[data-tab="legacy"]');if(tab){const count=tab.querySelector('span,em');if(count){const m=count.textContent.match(/(\d+)(?:\s*\/\s*(\d+))?/);if(m)count.textContent=(Number(m[1])+unlocked)+(m[2]?'/'+(Number(m[2])+allDefs.length):'');}}
  const profileCount=room.querySelector('.pac-profile p b');if(profileCount)profileCount.textContent=String((Number(profileCount.textContent)||0)+unlocked);
  const heading=panel.querySelector('header strong');if(heading){const m=heading.textContent.match(/(\d+)\s*\/\s*(\d+)/);if(m)heading.innerHTML=`${Number(m[1])+unlocked}<em>/${Number(m[2])+allDefs.length}</em>`;}
 }
 }
 function showStats(){observe();if(hooks?.openAchievements){hooks.openAchievements();return;}const button=document.querySelector('[data-action="open-achievements"]');button?.click();}
 document.addEventListener('DOMContentLoaded',()=>{new MutationObserver(()=>mountRecords()).observe(document.body,{childList:true,subtree:true});mountRecords();});
 const style=document.createElement('style');style.textContent='.parallel-career-tools{display:flex;gap:16px;padding:6px 16px;justify-content:flex-end;flex-wrap:wrap}.parallel-career-tools button{border:0;background:transparent;color:#203e39;border-radius:0;padding:4px 0;font:inherit;font-size:12px}.parallel-permanent{margin:0 12px 12px;padding:12px;border:1px solid #cab884;border-radius:10px;background:#f6f0dd;color:#283b32}.parallel-permanent div{padding:6px;border-top:1px solid #ddd}.parallel-extra-dialog{box-sizing:border-box;width:min(94vw,520px);max-height:90dvh;border:1px solid #c4b588;border-radius:16px;background:#faf7ef;color:#203e39;padding:20px;font-family:inherit;overflow:auto}.parallel-extra-dialog::backdrop{background:#0009}.parallel-extra-dialog header{display:flex;align-items:center;justify-content:space-between;gap:12px}.parallel-extra-dialog h2{font-size:22px}.parallel-extra-dialog button,.parallel-extra-dialog select,.parallel-extra-dialog input{font:inherit;padding:10px;border:1px solid #bbb49f;border-radius:8px;background:#fff;color:#203e39}.parallel-extra-dialog label{display:grid;gap:8px;margin:12px 0}.parallel-extra-dialog p,.parallel-record small{font-size:12px;line-height:1.7}.parallel-record{display:grid;grid-template-columns:1fr auto;gap:6px;padding:14px;margin:10px 0;border:1px solid #d5cdbb;border-radius:10px;background:#fff}.parallel-record small{grid-column:1/-1}.parallel-record a{font-size:11px;color:#55776a}.parallel-record.unlocked{border-color:#b49436;background:#fff6ce}.native-records-controls{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:12px 0}.native-records-controls nav{display:flex;gap:14px}.native-records-controls button{font:inherit;font-size:12px;border:0;background:transparent;padding:8px 0;color:inherit;border-bottom:2px solid transparent}.native-records-controls button[aria-pressed=true]{border-color:currentColor;font-weight:700}.native-records-controls select{font:inherit;font-size:12px;padding:6px;border:1px solid #dae3e4;background:white;color:inherit;border-radius:6px}.native-records-note{font-size:12px;color:#7a898c;line-height:1.6}.native-record-source{display:block;color:#7a898c;font-size:11px;margin-top:6px}[data-native-records] h4{margin:16px 0 8px}[data-native-records] .pac-locked h4{margin:0}[data-native-records] .achievement-legacy{opacity:1}[data-native-records] .achievement-legacy p{margin:6px 0}[data-native-records] .achievement-legacy em{font-size:12px}[data-native-records] .achievement-legacy-list{display:grid}';document.head.append(style);
 function wait(p,ms=15000){let timer;return Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('候选加载超时，请点击重新生成；已选能力会保留')),ms);})]).finally(()=>clearTimeout(timer));}
 function localIdentity(){db.localAccountId??='local-'+(window.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));save();return {accountId:db.localAccountId,name:db.draftName||'我的球员',avatar:''};}
 window.parallelCareer={localIdentity,wait,bind,name,prepare,summary,settle,remember:core.remember,showStats,attach:career=>{career.customName??=name();core.remember(career,career.seasonAugment);}};
})();
