/* Standalone adapter: no ads, no account bridge, no remote image requests. */
(() => {
 const BASE=new URL('.',document.currentScript.src).href;
 const abilities=['threePT','MID','FIN','DNK','HAN','PAS','PDEF','IDEF','BLK','REB','ATH','STR','CLU'];
 const core=window.ParallelCareerCore;
 const canon=core.franchise;
 const east=new Set(['ATL','BOS','BRK','CHI','CHO','CLE','DET','IND','MIA','MIL','NYK','ORL','PHI','TOR','WAS']);
 const hash=s=>{let n=2166136261;for(const c of String(s))n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0};
 const random=seed=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
 const cap=(n,a=25,b=99)=>Math.max(a,Math.min(b,n));
 const avg=r=>Math.round(abilities.reduce((s,k)=>s+(r[k]||50),0)/abilities.length);
 let historyPromise;const earlyPacks=new Map();let identityPromise;let talentsPromise;const talents=()=>talentsPromise??=fetch(BASE+'legacy-talents.json').then(r=>r.json());
 async function pack(season){const year=parseInt(season);const {HISTORY_PACKS}=await(historyPromise??=import(BASE+'dynasty-history-9ba1c1cf68e1.js'));if(year>=2000)return HISTORY_PACKS[Math.min(2025,year)];if(!earlyPacks.has(year))earlyPacks.set(year,(async()=>{const raw=await fetch(new URL('../assets/data/historical/player_seasons_'+(year+1)+'.json',BASE)).then(r=>r.json());const ids=await(identityPromise??=fetch(BASE+'player-identities.json').then(r=>r.json()));const config=window.__REGRET_STATIC__.seasons.find(s=>parseInt(s.season)===year);const teams=config.teams.map(t=>[t.abbreviation,t.team_id,t.name||t.abbreviation]);const players=raw.rows.filter(r=>r.type==='regular'&&r.gp>0&&r.team!=='TOT').map(r=>{const key=r.name.toLowerCase().replace(/[^a-z0-9]/g,'');const id=ids[key]||String(hash(r.realId));const o=Math.round(cap(48+r.ppg*1.2+r.rpg*.8+r.apg*1.3+r.spg*3+r.bpg*2));return [id,r.displayName||r.name,r.team,['PG','SG','SF','PF','C'][cap(r.position||3,1,5)-1],25,o,r.ppg,r.rpg,r.apg,r.spg,r.bpg,r.mins,r.gp,'历史球员',year-5,95];});return {teams,players};})());return earlyPacks.get(year);}

 let legendPromise;const normalize=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g,'');
 async function legends(){if(!legendPromise)legendPromise=Promise.all([fetch(BASE+'legend-profiles.json').then(r=>r.json()),identityPromise??=fetch(BASE+'player-identities.json').then(r=>r.json())]).then(([data,ids])=>{const byId=new Map(),byName=new Map();for(const team of data.teams){team.players=team.players.map(p=>Array.isArray(p)?{name:p[0],nameEn:p[1],positions:p[2],overall:p[3],ratings:Object.fromEntries(data.abilities.map((k,i)=>[k,p[4][i]]))}:p);}for(const team of data.teams)for(const p of team.players){p.player_id=Number(ids[normalize(p.nameEn)]||hash(p.nameEn));for(const k of [normalize(p.name),normalize(p.nameEn)])if(!byName.has(k)||byName.get(k).overall<p.overall)byName.set(k,p);if(!byId.has(p.player_id)||byId.get(p.player_id).overall<p.overall)byId.set(p.player_id,p);}return {data,byId,byName};});return legendPromise;}
 let profileIndex;
 function ratings(row){const o=row[5],score=row[6],reb=row[7],ast=row[8],stl=row[9],blk=row[10],pos=row[3],profile=profileIndex?.byId.get(Number(row[0]))||profileIndex?.byName.get(normalize(row[1]));if(profile){const difference=Math.min(0,o-profile.overall);return Object.fromEntries(abilities.map(k=>[k,Math.round(cap(profile.ratings[k]+difference*.55))]));}return Object.fromEntries(abilities.map(k=>[k,Math.round(cap(({threePT:score*1.3+(pos==='PG'||pos==='SG'?48:35),MID:score*1.1+48,FIN:score+48,DNK:o+(pos==='C'||pos==='PF'?5:-7),HAN:ast*5+48,PAS:ast*5+48,PDEF:stl*18+48,IDEF:blk*16+48,BLK:blk*19+42,REB:reb*4+38,ATH:o-3,STR:o+(pos==='C'?7:-8),CLU:o})[k]))]));}
 function candidate(row,season,p){const r=ratings(row);return {player_id:Number(row[0]),player:row[1],team:row[2],team_id:p.teams.find(t=>t[0]===row[2])?.[1]||0,draft_year:row[14],position:row[3],source_position:row[3],season,age:row[4],overall:row[5],abilities:abilities.map(ability=>({ability,player_id:Number(row[0]),player:row[1],season,team:row[2],team_id:p.teams.find(t=>t[0]===row[2])?.[1]||0,raw_rating:r[ability],final_rating:r[ability],retention:1,position:row[3]})),ratings:r,final_rating:row[5],ability_values:r,stats:{pts:row[6],reb:row[7],ast:row[8]},pts:row[6],reb:row[7],ast:row[8],min:row[11],games:row[12]};}
 window.parallelRefreshCandidates=async rows=>{profileIndex=await legends();return rows.map(c=>{const profile=profileIndex.byId.get(Number(c.player_id))||profileIndex.byName.get(normalize(c.player));if(!profile)return c;const rr=Object.fromEntries(abilities.map(k=>[k,Math.round(cap(profile.ratings[k]+Math.min(0,c.overall-profile.overall)*.55))]));return {...c,ratings:rr,ability_values:rr,abilities:c.abilities.map(a=>({...a,raw_rating:rr[a.ability],final_rating:rr[a.ability]}))};});};
 const selected=new Map();
 function legendCandidate(p,team,teamId){const r={...p.ratings};return {player_id:p.player_id,player:p.name,team,team_id:teamId,season:'all-time',source_label:'队史巅峰',position:p.positions[0],source_position:p.positions[0],overall:p.overall,ratings:r,ability_values:r,final_rating:p.overall,abilities:abilities.map(ability=>({ability,player_id:p.player_id,player:p.name,season:'all-time',team,team_id:teamId,raw_rating:r[ability],final_rating:r[ability],retention:1,position:p.positions[0]}))};}
 async function draft(d){profileIndex=await legends();const rng=random(hash(JSON.stringify(d))),seasons=window.__REGRET_STATIC__?.seasons||[];
 if((Number(d.round)+1)%4===0){let teams=profileIndex.data.teams.filter(t=>!d.lockedTeam||canon(t.abbreviation)===canon(d.lockedTeam));if(!teams.length)teams=profileIndex.data.teams;const team=teams[Math.floor(rng()*teams.length)],teamId=seasons.flatMap(s=>s.teams).find(t=>canon(t.abbreviation)===canon(team.abbreviation))?.team_id||0;let pool=team.players.filter(p=>!d.excludedIds?.includes(p.player_id)&&!d.previousCandidateIds?.includes(p.player_id));if(pool.length<3)pool=team.players.filter(p=>!d.excludedIds?.includes(p.player_id));for(let i=pool.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}if(d.qualityMode)pool.sort((a,b)=>b.overall-a.overall);const candidates=pool.slice(0,d.qualityMode?5:3).map(p=>legendCandidate(p,team.abbreviation,teamId));for(const c of candidates)selected.set(c.player_id+':'+c.season,c);return {season:'all-time',team:team.abbreviation,team_id:teamId,candidates};}
 const season=d.lockedSeason&&d.lockedSeason!=='all-time'?d.lockedSeason:seasons[Math.floor(rng()*seasons.length)]?.season||'2017-18',p=await pack(season);let teams=p.teams.filter(t=>!d.lockedTeam||canon(t[0])===canon(d.lockedTeam));if(!teams.length)teams=p.teams;const team=teams[Math.floor(rng()*teams.length)];let rows=p.players.filter(r=>canon(r[2])===canon(team[0])&&!d.excludedIds?.includes(Number(r[0]))&&!d.previousCandidateIds?.includes(Number(r[0])));if(rows.length<3)rows=p.players.filter(r=>canon(r[2])===canon(team[0]));if(d.qualityMode)rows=rows.slice().sort((a,b)=>b[5]-a[5]).slice(0,6);else for(let i=rows.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[rows[i],rows[j]]=[rows[j],rows[i]];}const candidates=rows.slice(0,d.qualityMode?5:3).map(r=>candidate(r,season,p));for(const c of candidates)selected.set(c.player_id+':'+c.season,c);return {season,team:d.lockedTeam||team[0],team_id:team[1],candidates};}
 async function assembled(d){profileIndex=await legends();if(d.current_ratings)return {...d.current_ratings};const r={};for(const k of abilities){const donor=d.donors[k];let c=selected.get(donor.player_id+':'+donor.season);if(!c&&donor.season==='all-time'){const profile=profileIndex.byId.get(Number(donor.player_id))||profileIndex.byName.get(normalize(donor.player));if(profile)c=legendCandidate(profile,donor.team,donor.team_id);}if(!c){const p=await pack(donor.season);const row=p.players.find(x=>Number(x[0])===donor.player_id||x[1]===donor.player);if(row)c=candidate(row,donor.season,p);}r[k]=Number.isFinite(donor.final_rating)?donor.final_rating:c?.ratings[k]||75;}return r;}
 // Positions affect opportunity, not a position-specific statistical ceiling.
 const positionRates={PG:{reb:.59,ast:1},SG:{reb:.56,ast:.9},SF:{reb:.66,ast:.83},PF:{reb:.79,ast:.76},C:{reb:1,ast:.68}};
 function skillProduction(skill,slope,eliteSlope,overflowSlope){
  const elite=Math.max(0,Math.min(skill,99)-85);
  return Math.max(0,(skill-35)*slope+elite*elite*eliteSlope+Math.max(0,skill-99)*overflowSlope);
 }
 function line(r,rng,position='SF',minutesBonus=0){
  const o=avg(r),min=cap(18+(o-60)*.6+minutesBonus,12,48),opportunity=Math.sqrt(min/33);
  const rates=positionRates[position]||positionRates.SF;
  // Rebounding needs positioning, strength and athleticism; creation needs passing, handle and decisions.
  const reboundSkill=r.REB*.7+r.STR*.18+r.ATH*.12;
  const assistSkill=r.PAS*.75+r.HAN*.15+r.CLU*.1;
  const reboundMean=(.5+skillProduction(reboundSkill,.22,.035,.35))*rates.reb*opportunity;
  const assistMean=skillProduction(assistSkill,.18,.033,.24)*rates.ast*opportunity;
  let pts=Math.max(0,Math.round(((r.threePT+r.MID+r.FIN)/3-40)*.55*(.65+rng()*.7)));
  let reb=Math.max(0,Math.round(reboundMean*(.6+rng()*.8)));
  let ast=Math.max(0,Math.round(assistMean*(.6+rng()*.8)));
  const stealSkill=r.PDEF*.55+r.HAN*.1+r.ATH*.2+r.CLU*.15,blockSkill=r.BLK*.55+r.IDEF*.25+r.ATH*.2;
  const poisson=mean=>{let n=0,p=1,limit=Math.exp(-Math.max(0,mean));do{n++;p*=rng();}while(p>limit&&n<40);return n-1;};
  const stealRate={PG:1.12,SG:1.06,SF:1,PF:.9,C:.85}[position]||1;
  const blockRate={PG:.32,SG:.4,SF:.58,PF:.85,C:1}[position]||1;
  let stl=poisson(Math.max(0,(stealSkill-40)*.045)*stealRate*opportunity),blk=poisson(Math.max(0,(blockSkill-40)*.085)*blockRate*opportunity);
  let explosion=false;
  if(min>=38&&stealSkill>=96&&blockSkill>=96&&reboundSkill>=96&&assistSkill>=96&&Math.min(r.FIN,r.MID)>=95&&rng()<.0003){stl=10+Math.floor(rng()*3);blk=10+Math.floor(rng()*6);reb=Math.max(reb,10);ast=Math.max(ast,10);explosion=true;}
  if(min>=38&&reboundSkill>=98&&rng()<.0006)reb=50+Math.floor(rng()*12);
  if(min>=36&&assistSkill>=97&&rng()<.001)ast=28+Math.floor(rng()*9);
  if(min>=38&&Math.min(r.threePT,r.MID,r.FIN,r.HAN,r.CLU)>=98&&rng()<.0006)pts=85+Math.floor(rng()*26);
  const fga=Math.max(Math.ceil(pts/2),Math.round(pts/1.5)),fgm=Math.min(fga,Math.round(pts*.34)),threeMade=Math.min(fgm,Math.round(pts*.09));
  return {min,pts,reb,ast,stl,blk,legendary_performance:explosion,tov:Math.round(rng()*4),fgm,fga,fg_pct:fga?fgm/fga:0,three_m:threeMade,three_a:Math.max(threeMade,Math.round(threeMade*2.7)),three_made:threeMade,three_attempts:Math.max(threeMade,Math.round(threeMade*2.7)),three_pct:.36,ftm:Math.max(0,pts-fgm*2-threeMade),fta:Math.max(0,pts-fgm*2-threeMade+1),ft_pct:.8,starter:o>=72,played:true,points:pts,rebounds:reb,assists:ast};
 }
 function distribute(total,weights){const sum=weights.reduce((a,b)=>a+b,0)||1,out=weights.map(w=>Math.floor(total*w/sum));let left=total-out.reduce((a,b)=>a+b,0);const order=weights.map((w,i)=>({i,rem:total*w/sum-out[i]})).sort((a,b)=>b.rem-a.rem);for(let i=0;i<left;i++)out[order[i%order.length].i]++;return out;}
 function finishGame(g,roster,team,player,rng){
  const own=g.home===team?'home_score':'away_score',enemy=own==='home_score'?'away_score':'home_score',won=g.winner===team;
  const l=g.player_line;l.min=Math.round(l.min);
  g[own]=Math.max(g[own],l.pts+Math.max(28,l.ast*2+12));
  if(won&&g[own]<=g[enemy])g[own]=g[enemy]+1;else if(!won&&g[enemy]<=g[own])g[enemy]=g[own]+1+Math.floor(rng()*10);
  g.box_score={};
  for(const t of [g.home,g.away]){
   const self=t===team,rows=(roster[t]||[]).slice(0,self?8:9),score=t===g.home?g.home_score:g.away_score;
   const weights=rows.map(x=>Math.max(1,x.pts)*(.75+rng()*.5)),points=distribute(score-(self?l.pts:0),weights);
   const minutes=distribute(240-(self?l.min:0),rows.map(x=>Math.max(10,x.min||20)));for(let i=0;i<minutes.length;i++)while(minutes[i]>48){const j=minutes.findIndex((m,k)=>k!==i&&m<48);if(j<0)break;minutes[i]--;minutes[j]++;}
   const boards=distribute(Math.max(8,43-(self?l.reb:0)),rows.map(x=>Math.max(1,x.reb)*(.7+rng()*.6)));
   const assists=distribute(Math.max(3,23-(self?l.ast:0)),rows.map(x=>Math.max(1,x.ast)));
   const lines=rows.map((x,i)=>{const pts=points[i],fgm=Math.floor(pts/2),ftm=pts-fgm*2;return {...x,starter:i<5,min:minutes[i],pts,reb:boards[i],ast:assists[i],stl:Math.floor(rng()*3),blk:Math.floor(rng()*3),tov:Math.floor(rng()*4),fgm,fga:fgm+Math.ceil(fgm*.65),three_m:0,three_a:0,three_made:0,three_attempts:0,ftm,fta:ftm,fg_pct:fgm?fgm/(fgm+Math.ceil(fgm*.65)):0,ft_pct:ftm?1:0,three_pct:0,played:true};});
   if(self)lines.unshift({player:'我',name:player.name||'我的球员',player_id:-1,position:player.position,composite:true,starter:true,...l});
   g.box_score[t]=lines;
  }
 }
 function honor(c,l,user=false){const stats={...l};for(const k of ['pts','reb','ast','stl','blk','min'])if(Number.isFinite(stats[k]))stats[k]=Math.round(stats[k]*10)/10;return {...c,...stats,is_user:user,name:c.player,score:stats.pts||0,line:`${stats.pts||0}分 · ${stats.reb||0}篮板 · ${stats.ast||0}助攻`};}
 async function simulate(d){const p=await pack(d.season),rng=random(d.seed||1),r=await assembled(d.player),o=avg(r),player={...d.player,ratings:r,overall:o,player:'我',player_id:-1},team=core.teamAt(d.team,d.career_context?.display_season||d.season),season=d.career_context?.display_season||d.season;let augment=d.career_context?.augment;const permanent=core.augments(d.career_context);const baseRatings={...r};let boostKeys=[];for(const savedAugment of permanent){const augment=savedAugment;const keys={three:['threePT'],mid:['MID'],finish:['FIN'],dunk:['DNK'],handle:['HAN'],pass:['PAS'],perimeter:['PDEF'],interior:['IDEF'],block:['BLK'],rebound:['REB'],athletic:['ATH'],strength:['STR'],creator:['HAN','PAS'],sniper:['HAN','threePT'],driver:['HAN','FIN'],'two-way':['MID','PDEF'],'three-d':['threePT','PDEF'],air:['DNK','ATH'],hub:['PAS','IDEF'],paint:['FIN','REB']};boostKeys=keys[augment.id]||[];if(augment.id==='weakness'&&abilities.includes(augment.choice))boostKeys=[augment.choice];for(const key of boostKeys)r[key]=cap(r[key]+augment.tier*2/boostKeys.length,25,110);if(augment.id==='borrow'){const borrowed=(await talents()).find(t=>t.id===augment.choice);if(borrowed)for(const[k,v]of Object.entries(borrowed.boosts))r[k]=cap(r[k]+v,25,110);}}
 function gameRatings(home,playoff){const rr={...r};for(const augment of permanent){if(augment?.id==='home-away'){const key=home===team?'MID':'threePT';rr[key]=cap(rr[key]+augment.tier*2,25,110);}if(augment?.id==='postseason'){const key=playoff?'FIN':'threePT';rr[key]=cap(rr[key]+augment.tier*2,25,110);}if(augment?.id==='wildcard'){const key=['threePT','MID','FIN'][Math.floor(rng()*3)];rr[key]=cap(rr[key]+augment.tier*2,25,110);}if(augment?.id==='ageless')for(const k of ['ATH','DNK'])rr[k]=cap(rr[k]+Math.max(0,(d.career_context?.age||20)-34)*augment.tier*.3,25,110);}return rr;}

 const roster={};for(const t of p.teams)roster[t[0]]=p.players.filter(x=>x[2]===t[0]).map(x=>({...candidate(x,season,p),composite:false,starter:x[11]>=25,tov:2,stl:x[9],blk:x[10],ratings:ratings(x)}));roster[team]=roster[team]||roster[canon(team)]||Object.entries(roster).find(([t])=>canon(t)===canon(team))?.[1]||[];
 const strength=roster[team].slice(0,8).reduce((s,x)=>s+x.overall,0)/8;
 const winRate=cap(.48+(strength-72)*.013+(o-72)*.009+Number(d.reward_context?.trade_deadline?.team_strength_delta||0)*.05,.15,.85);
 const games=[];for(let i=0;i<82;i++){const opponent=p.teams[(i*7+Math.floor(rng()*29))%p.teams.length][0];const other=canon(opponent)===canon(team)?p.teams.find(t=>canon(t[0])!==canon(team))[0]:opponent;const won=rng()<winRate,home=i%2?other:team,away=i%2?team:other,winScore=Math.round(104+rng()*28),loseScore=winScore-Math.round(1+rng()*16),l=line(gameRatings(home,false),rng,player.position,permanent.filter(a=>a.id==='endurance').reduce((n,a)=>n+a.tier*2,0));games.push({game:i+1,home,away,winner:won?team:other,home_score:home===(won?team:other)?winScore:loseScore,away_score:away===(won?team:other)?winScore:loseScore,player_line:l,box_score:{[team]:[{player:'我',player_id:-1,position:player.position,composite:true,starter:true,...l},...roster[team].slice(0,8)],[other]:(roster[other]||[]).slice(0,9)},overtime:0,narrative:won?'球队把握住关键回合，拿下胜利。':'最后的追分没能逆转，下一场继续。',events:[],clutch_events:[],date:`${season}:${i+1}`});}
 for(const g of games)finishGame(g,roster,team,player,rng);
 const wins=games.filter(g=>g.winner===team).length,seed=cap(Math.round((65-wins)/3)+1,1,15),made=seed<=8;
 const averages={games:82};for(const k of ['pts','reb','ast','stl','blk','tov','min','fgm','fga','three_made','three_attempts','ftm','fta'])averages[k]=Math.round(games.reduce((s,g)=>s+g.player_line[k],0)/82*10)/10;Object.assign(averages,{fg_pct:averages.fgm/averages.fga,three_pct:.36,ft_pct:.8});
 const rows=Object.values(roster).flat(),entries=rows.filter(x=>x.min>25).sort((a,b)=>b.pts-a.pts).map(c=>honor(c,c)),user=honor({player:'我',player_id:-1,team,position:player.position},averages,true);
 const pick=(yes,idx=0)=>yes?user:entries[idx]||user;const top=entries.slice(0,15);if(o>=82)top[0]=user;
 const rookie=entries.filter(x=>x.draft_year===parseInt(d.season)).sort((a,b)=>b.pts-a.pts)[0]||entries.find(x=>x.age<=22)||entries[0];const sixth=entries.filter(x=>x.min<26).sort((a,b)=>b.pts-a.pts)[0]||entries[3];const defensiveScore=(x,rr)=>{const inside=['C','PF'].includes(x.position);return (inside?rr.IDEF*.6+rr.PDEF*.1+rr.BLK*.3:rr.PDEF*.7+rr.IDEF*.2+rr.BLK*.1)+Number(x.stl||0)*2+Number(x.blk||0)*2;};const defenders=[...rows.filter(x=>x.min>=18).map(x=>({...honor(x,x),defensive_score:defensiveScore(x,x.ratings)})),{...user,defensive_score:defensiveScore(user,r)}].sort((a,b)=>b.defensive_score-a.defensive_score);const honors={mvp:pick(o>=93&&wins>=55),scoring_champion:pick(averages.pts>30),dpoy:defenders[0],roy:(d.career_context?.career_year||1)===1&&o>=80?user:rookie,sixth_man:sixth,all_nba:{first:top.slice(0,5),second:top.slice(5,10),third:top.slice(10,15)},all_defense:{first:defenders.slice(0,5),second:defenders.slice(5,10)},all_star:{selected:o>=80?[user,...entries.slice(0,23)]:entries.slice(0,24)}};
 const series=[];const faced=new Set([canon(team)]);let survived=made;for(const round of ['R1','WCSF','WCF','Finals']){if(!survived)break;let eligible=p.teams.filter(t=>!faced.has(canon(t[0]))&&(round==='Finals'?east.has(canon(t[0]))!==east.has(canon(team)):east.has(canon(t[0]))===east.has(canon(team))));if(!eligible.length)eligible=p.teams.filter(t=>canon(t[0])!==canon(team));const opponent=eligible[Math.floor(rng()*eligible.length)][0];faced.add(canon(opponent));let a=0,b=0,sg=[];while(a<4&&b<4){const won=rng()<cap(winRate-.04,.2,.78),home=sg.length%2?opponent:team,away=sg.length%2?team:opponent,l=line(gameRatings(home,true),rng,player.position,permanent.filter(a=>a.id==='endurance').reduce((n,a)=>n+a.tier*2,0)),hi=Math.round(100+rng()*28),lo=hi-Math.round(1+rng()*14);won?a++:b++;sg.push({game:sg.length+1,round,home,away,winner:won?team:opponent,home_score:home===(won?team:opponent)?hi:lo,away_score:away===(won?team:opponent)?hi:lo,player_line:l,box_score:{[team]:[{player:'我',player_id:-1,position:player.position,starter:true,composite:true,...l},...roster[team].slice(0,8)],[opponent]:(roster[opponent]||[]).slice(0,9)},events:[],clutch_events:[]});}survived=a===4;series.push({round:round==='WCSF'&&east.has(canon(team))?'ECSF':round==='WCF'&&east.has(canon(team))?'ECF':round,teams:[team,opponent],winner:survived?team:opponent,games:sg,series:{[team]:a,[opponent]:b},locked_before_entry:{[team]:0,[opponent]:0}});}
 for(const g of series.flatMap(s=>s.games))finishGame(g,roster,team,player,rng);
 const champion=survived?team:series.at(-1)?.winner||p.teams[Math.floor(rng()*p.teams.length)][0];const standings={East:[],West:[]};for(const t of p.teams){const w=canon(t[0])===canon(team)?wins:Math.round(24+rng()*40),row={team:t[0],team_id:t[1],wins:w,losses:82-w,win_pct:w/82,seed:1};(east.has(canon(t[0]))?standings.East:standings.West).push(row);}for(const a of Object.values(standings))a.sort((a,b)=>b.wins-a.wins).forEach((x,i)=>x.seed=i+1);
 const result={simulation_version:'career-v3',mode:'season',season,source_season:d.season,team,team_label:team,team_id:p.teams.find(x=>canon(x[0])===canon(team))?.[1],seed:d.seed,career_year:d.career_context?.career_year||1,data_mode:parseInt(season)>2025?'projected':'historical',player:{...player,ratings:baseRatings},roster_snapshot:roster,retiring_teammates:[],standings,regular_season:{record:{wins,losses:82-wins},conference_seed:seed,games,player_averages:averages,player_availability:{games:82,available_games:82,missed_games:0,injuries:[],notes:[]},player_role:{starter:true,role:'核心',minutes:averages.min},roster_simulation:{}},play_in_games:[],playoff_series:series,league_honors:honors,finals_mvp:survived?user:entries[0],outcome:{champion,won_title:survived,made_playoffs:made,history_changed:true},narrative:[],stories:[],team_strength:strength};
 result.parallel_stats=core.resultStats(result);result.permanent_augments=permanent;result.player.name=d.player.name||'我的球员';
 boostKeys=({three:['threePT'],mid:['MID'],finish:['FIN'],dunk:['DNK'],handle:['HAN'],pass:['PAS'],perimeter:['PDEF'],interior:['IDEF'],block:['BLK'],rebound:['REB'],athletic:['ATH'],strength:['STR'],creator:['HAN','PAS'],sniper:['HAN','threePT'],driver:['HAN','FIN'],'two-way':['MID','PDEF'],'three-d':['threePT','PDEF'],air:['DNK','ATH'],hub:['PAS','IDEF'],paint:['FIN','REB'],weakness:[augment?.choice]})[augment?.id]||[];
 if(augment){result.augment_result={version:1,id:augment.id,effects:boostKeys.map(ability=>({ability,delta:augment.tier*2/boostKeys.length})),boosts:augment.boosts||{},earned:augment.reaperChoice||null};if(augment.id==='reaper'&&series.some(s=>s.winner===team)){const skills=await talents();const beaten=series.find(s=>s.winner===team),ids=(roster[beaten.teams.find(t=>t!==team)]||[]).map(x=>Number(x.player_id)),available=skills.filter(x=>ids.includes(x.playerId));if(available.length)result.augment_result.opportunity={round:beaten.round,options:available.slice(0,3).map(s=>s.id)};}}if(permanent.some(a=>a.id==='reaper')&&series.some(s=>s.winner===team)){const skills=await talents(),ids=series.filter(s=>s.winner===team).flatMap(s=>(roster[s.teams.find(t=>t!==team)]||[]).map(x=>Number(x.player_id))),available=skills.filter(s=>ids.includes(s.playerId));result.permanent_opportunities=permanent.filter(a=>a.id==='reaper'&&a.key!==augment?.key).map(a=>({key:a.key,options:available.map(s=>s.id),skills:available.map(s=>({id:s.id,mentor:s.mentor,name:s.name}))}));}const bf=d.career_context?.butterfly;if(bf)result.butterfly={...bf,version:1,stats_version:1,year:parseInt(season),token:bf.token||'local-league',echoes:[],closing_echoes:[]};return result;
 }
 window.parallelRepairResult=result=>{if(!result||result.mode!=='season'||result.simulation_version==='career-v3'||result.parallel_boxes_repaired)return;const roster=result.roster_snapshot||{},rng=random((result.seed||1)^1729);for(const g of [...(result.regular_season?.games||[]),...(result.playoff_series||[]).flatMap(s=>s.games)])if(g.player_line)finishGame(g,roster,result.team,result.player,rng);result.parallel_boxes_repaired=true;result.parallel_stats=core.resultStats(result);};
 async function teamRoster(season,team){profileIndex=await legends();const p=await pack(season);const projected=Math.max(0,parseInt(season)-2025);return p.players.filter(x=>canon(x[2])===canon(team)).map(x=>{const c=candidate(x,season,p);c.team=core.teamAt(team,season);c.age=(Number(c.age)||25)+projected;c.contract={years_remaining:Math.max(1,3-projected%3),annual_salary_millions:Math.round(Math.max(1,(c.overall-55)*.7)*10)/10};return c;});}
 window.parallelRequest=async(path,opts={})=>{
  const d=opts.data||{};
  if(path==='/team-offers')return draft(d);
  if(path==='/team-roster')return {roster:await teamRoster(d.season,d.team)};
  if(path==='/simulate')return simulate(d);
  if(path==='/seasons')return {seasons:window.__REGRET_STATIC__.seasons};
  if(path==='/career/augment-options'){const p=await pack(d.season),skills=await talents();const matches=(s,r)=>s.playerId===Number(r[0])||s.mentor===r[1]||s.aliases.some(a=>a.replace(/[^a-z]/gi,'').toLowerCase()===r[1].replace(/[^a-z]/gi,'').toLowerCase());return {version:1,available:skills.filter(s=>p.players.some(r=>matches(s,r))).map(s=>s.id),teammates:skills.filter(s=>p.players.some(r=>canon(r[2])===canon(d.team)&&matches(s,r))).map(s=>s.id)};}
  if(path==='/career/develop'){
   const ratings={...d.player.ratings},before=avg(ratings),age=d.age||20,changes=[],resistance=cap((d.permanent_augments||[]).filter(a=>a.id==='ageless').reduce((n,a)=>n+a.tier*.1,0),0,.8);
   if(age>=31)for(const k of abilities){const delta=(['ATH','DNK','STR'].includes(k)?-2:-1)*(1-resistance);const from=ratings[k],to=Math.round(cap(from+delta)*10)/10;changes.push({ability:k,from,to,delta:to-from});ratings[k]=to;}
   return {ratings,potentials:Object.fromEntries(abilities.map(k=>[k,99])),age_before:age,age_after:age+1,overall_before:before,overall_after:avg(ratings),growth_points:age<27?6:age<32?3:1,changes,reason:resistance?'永久长青海克斯减缓年龄衰减':'训练与年龄共同影响本季成长'};
  }
  if(path==='/career/next-season'){const y=parseInt(d.season)+1;return {season:y+'-'+String((y+1)%100).padStart(2,'0'),source_season:y>2025?'2025-26':y+'-'+String((y+1)%100).padStart(2,'0'),team:core.teamAt(d.team,y),franchise_id:canon(d.team),projected:y>2025,projection_year:Math.max(0,y-2025)};}
  if(path==='/career/offers'){
   const year=parseInt(d.season)+1,season=year+'-'+String((year+1)%100).padStart(2,'0'),p=await pack(season),rng=random(d.seed||1),stay=p.teams.find(x=>canon(x[0])===canon(d.team));
   if(!stay)throw Error('当前球队在下一赛季不存在，请检查球队身份');
   const shuffled=p.teams.filter(x=>canon(x[0])!==canon(d.team));for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}
   const teams=[stay,...shuffled.slice(0,3)],offers=[];
   for(const [i,t]of teams.entries()){const team=core.teamAt(t[0],year),roster=await teamRoster(season,team),record=Object.entries(d.league_records||{}).find(([key])=>canon(key)===canon(team))?.[1]||{wins:45,losses:37};offers.push({id:'local-'+canon(team)+'-'+d.seed,team,franchise_id:canon(team),role:'核心轮换',kind:i?'contender':'stay',annual_salary_millions:Math.round((d.player.overall||75)*.3),reason:i?'球队希望与你一起争夺冠军':'原球队希望你继续带队',team_record:record,title_odds:record.wins>=50?'争冠热门':record.wins>=40?'季后赛竞争者':'重建与成长',position_fit:'按阵容评估同位置竞争',roster,years:3,projected:year>2025});}
   return {offers,butterfly:d.butterfly?{...d.butterfly,version:1,year}:undefined};
  }
  if(path.includes('save'))return null;
  if(path.includes('ranking')||path.includes('leaderboard'))return {entries:[],rows:[],total:0,page:1};
  throw Error('暂未支持的本地流程：'+path);
 };
 const noop=()=>{};
 window.ColorboxAI={configure:noop,track:noop,log:noop,event:noop,auth:{getUserInfo:async()=>null},storage:null,cloud:{auth:async()=>({code:200}),request:async({url,data,method})=>({code:200,statusCode:200,data:await window.parallelRequest(new URL(url,location.href).pathname,{data,method})})},navigateTo:noop,request:{},security:{checkAudit:async()=>({code:200})}};
 window.VaFuSDK={isInApp:true,getIsLogin:async()=>false,getUserInfo:async()=>null,track:noop,completeRewardVideoTask:async()=>({ok:true}),getActivityTaskState:async()=>({ok:true,state:{tasks:[{status:'pending',action:{kind:'reward_video'}}]}})};
 function notice(title){let d=document.getElementById('parallel-disabled');if(!d){d=document.createElement('dialog');d.id='parallel-disabled';d.style.cssText='max-width:320px;border:1px solid #d7cfc2;border-radius:18px;background:#faf7f0;padding:24px;color:#25251f;box-shadow:0 20px 80px #0004;font-family:inherit';d.innerHTML='<h3></h3><p>此模式仅保留入口，未制作内部内容。</p><button style="padding:10px 25px;border:0;border-radius:10px;background:#263f37;color:white">返回游戏</button>';d.querySelector('button').onclick=()=>d.close();document.body.append(d);}d.querySelector('h3').textContent=title;d.showModal();}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-star-cards-open],button');if(!b)return;const a=b.dataset.action||'';let title;if(b.matches('[data-star-cards-open]'))title='我的梦之队';if(['choose-regret','resume-home-regret'].includes(a))title='回到一场球';if(/trinity/.test(a)&&/^(start|resume|open)/.test(a))title='他化自在';if(title){e.preventDefault();e.stopImmediatePropagation();notice(title);}},true);
 // Preserve image-based rendering even when an upstream spelling has changed.
 let mapping;window.parallelAssetMap=fetch(BASE+'asset-manifest.json').then(r=>r.json()).then(m=>mapping=m.files);
 const roots=new Set();
 const fix=img=>{const src=img.getAttribute('src');if(mapping?.[src])img.setAttribute('src',mapping[src]);img.decoding='async';};
 const remap=root=>{for(const e of root.querySelectorAll?.('button small,button span')||[])if(e.textContent.trim()==='广告')e.textContent='免费';if(root.matches?.('img[src]'))fix(root);for(const img of root.querySelectorAll?.('img[src]')||[])fix(img);for(const el of root.querySelectorAll?.('*')||[])if(el.shadowRoot)watch(el.shadowRoot);};
 function watch(root){if(roots.has(root))return;roots.add(root);remap(root);new MutationObserver(rs=>{for(const r of rs){if(r.type==='attributes')fix(r.target);else for(const n of r.addedNodes)if(n.nodeType===1)remap(n);}}).observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:['src']});}
 const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(options){const root=attach.call(this,options);watch(root);return root;};
 document.addEventListener('DOMContentLoaded',()=>{watch(document);window.parallelAssetMap.then(()=>{for(const root of roots)remap(root);});});
})();
