/* Standalone adapter: no ads, no account bridge, no remote image requests. */
(() => {
 const BASE=new URL('.',document.currentScript.src).href;
 const abilities=['threePT','MID','FIN','DNK','HAN','PAS','PDEF','IDEF','BLK','REB','ATH','STR','CLU'];
 const canon=t=>({BKN:'BRK',NJN:'BRK',PHX:'PHO',SEA:'OKC',VAN:'MEM',NOH:'NOP',NOK:'NOP',WSB:'WAS',CHH:'CHO',CHA:'CHO'}[t]||t);
 const hash=s=>{let n=2166136261;for(const c of String(s))n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0};
 const random=seed=>()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
 const cap=(n,a=25,b=99)=>Math.max(a,Math.min(b,n));
 const avg=r=>Math.round(abilities.reduce((s,k)=>s+(r[k]||50),0)/abilities.length);
 let historyPromise;const earlyPacks=new Map();let identityPromise;let talentsPromise;const talents=()=>talentsPromise??=fetch(BASE+'legacy-talents.json').then(r=>r.json());
 async function pack(season){const year=parseInt(season);const {HISTORY_PACKS}=await(historyPromise??=import(BASE+'dynasty-history-9ba1c1cf68e1.js'));if(year>=2000)return HISTORY_PACKS[Math.min(2025,year)];if(!earlyPacks.has(year))earlyPacks.set(year,(async()=>{const raw=await fetch(new URL('../assets/data/historical/player_seasons_'+(year+1)+'.json',BASE)).then(r=>r.json());const ids=await(identityPromise??=fetch(BASE+'player-identities.json').then(r=>r.json()));const config=window.__REGRET_STATIC__.seasons.find(s=>parseInt(s.season)===year);const teams=config.teams.map(t=>[t.abbreviation,t.team_id,t.name||t.abbreviation]);const players=raw.rows.filter(r=>r.type==='regular'&&r.gp>0&&r.team!=='TOT').map(r=>{const key=r.name.toLowerCase().replace(/[^a-z0-9]/g,'');const id=ids[key]||String(hash(r.realId));const o=Math.round(cap(48+r.ppg*1.2+r.rpg*.8+r.apg*1.3+r.spg*3+r.bpg*2));return [id,r.displayName||r.name,r.team,['PG','SG','SF','PF','C'][cap(r.position||3,1,5)-1],25,o,r.ppg,r.rpg,r.apg,r.spg,r.bpg,r.mins,r.gp,'历史球员',year-5,95];});return {teams,players};})());return earlyPacks.get(year);}

 function ratings(row){const o=row[5],score=row[6],reb=row[7],ast=row[8],stl=row[9],blk=row[10],pos=row[3];return Object.fromEntries(abilities.map(k=>[k,Math.round(cap(({threePT:score*1.3+(pos==='PG'||pos==='SG'?48:35),MID:score*1.1+48,FIN:score+48,DNK:o+(pos==='C'||pos==='PF'?5:-7),HAN:ast*5+48,PAS:ast*5+48,PDEF:stl*18+48,IDEF:blk*16+48,BLK:blk*19+42,REB:reb*4+38,ATH:o-3,STR:o+(pos==='C'?7:-8),CLU:o})[k]))]));}
 function candidate(row,season,p){const r=ratings(row);return {player_id:Number(row[0]),player:row[1],team:row[2],team_id:p.teams.find(t=>t[0]===row[2])?.[1]||0,position:row[3],source_position:row[3],season,age:row[4],overall:row[5],abilities:abilities.map(ability=>({ability,player_id:Number(row[0]),player:row[1],season,team:row[2],team_id:p.teams.find(t=>t[0]===row[2])?.[1]||0,raw_rating:r[ability],final_rating:r[ability],retention:1,position:row[3]})),ratings:r,final_rating:row[5],ability_values:r,stats:{pts:row[6],reb:row[7],ast:row[8]},pts:row[6],reb:row[7],ast:row[8],min:row[11],games:row[12]};}
 const selected=new Map();
 async function draft(d){const rng=random(hash(JSON.stringify(d))),seasons=window.__REGRET_STATIC__?.seasons||[];const season=d.lockedSeason||seasons[Math.floor(rng()*seasons.length)]?.season||'2017-18',p=await pack(season);let teams=p.teams.filter(t=>!d.lockedTeam||canon(t[0])===canon(d.lockedTeam));if(!teams.length)teams=p.teams;const team=teams[Math.floor(rng()*teams.length)];let rows=p.players.filter(r=>canon(r[2])===canon(team[0])&&!d.excludedIds?.includes(Number(r[0]))&&!d.previousCandidateIds?.includes(Number(r[0])));if(rows.length<3)rows=p.players.filter(r=>canon(r[2])===canon(team[0]));if(d.qualityMode)rows=rows.slice().sort((a,b)=>b[5]-a[5]).slice(0,6);else rows=rows.slice().sort(()=>rng()-.5);const candidates=rows.slice(0,d.qualityMode?5:3).map(r=>candidate(r,season,p));for(const c of candidates)selected.set(c.player_id+':'+c.season,c);return {season,team:d.lockedTeam||team[0],team_id:team[1],candidates};}
 async function assembled(d){if(d.current_ratings)return {...d.current_ratings};const r={};for(const k of abilities){const donor=d.donors[k];let c=selected.get(donor.player_id+':'+donor.season);if(!c){const p=await pack(donor.season);const row=p.players.find(x=>Number(x[0])===donor.player_id||x[1]===donor.player);if(row)c=candidate(row,donor.season,p);}r[k]=c?.ratings[k]||75;}return r;}
 function line(r,rng){const o=avg(r),min=cap(18+(o-60)*.6,12,38);const pts=Math.max(0,Math.round(((r.threePT+r.MID+r.FIN)/3-40)*.55*(.65+rng()*.7)));const reb=Math.max(0,Math.round((r.REB-35)*.16*(.6+rng()*.8))),ast=Math.max(0,Math.round((r.PAS-40)*.15*(.6+rng()*.8)));const fga=Math.max(pts/2,Math.round(pts/1.5)),fgm=Math.min(fga,Math.round(pts*.34)),threeMade=Math.min(fgm,Math.round(pts*.09));return {min,pts,reb,ast,stl:Math.round((r.PDEF-40)*.035*rng()),blk:Math.round((r.BLK-40)*.04*rng()),tov:Math.round(rng()*4),fgm,fga,fg_pct:fga?fgm/fga:0,three_m:threeMade,three_a:Math.max(threeMade,Math.round(threeMade*2.7)),three_made:threeMade,three_attempts:Math.max(threeMade,Math.round(threeMade*2.7)),three_pct:.36,ftm:Math.max(0,pts-fgm*2-threeMade),fta:Math.max(0,pts-fgm*2-threeMade+1),ft_pct:.8,starter:o>=72,played:true,points:pts,rebounds:reb,assists:ast};}
 function honor(c,l,user=false){return {...c,...l,is_user:user,name:c.player,score:l.pts||0,line:`${l.pts||0}分 · ${l.reb||0}篮板 · ${l.ast||0}助攻`};}
 async function simulate(d){const p=await pack(d.season),rng=random(d.seed||1),r=await assembled(d.player),o=avg(r),player={...d.player,ratings:r,overall:o,player:'我',player_id:-1},team=d.team,season=d.career_context?.display_season||d.season;let augment=d.career_context?.augment;const baseRatings={...r};let boostKeys=[];if(augment){const keys={three:['threePT'],mid:['MID'],finish:['FIN'],dunk:['DNK'],handle:['HAN'],pass:['PAS'],perimeter:['PDEF'],interior:['IDEF'],block:['BLK'],rebound:['REB'],athletic:['ATH'],strength:['STR'],creator:['HAN','PAS'],sniper:['HAN','threePT'],driver:['HAN','FIN'],'two-way':['MID','PDEF'],'three-d':['threePT','PDEF'],air:['DNK','ATH'],hub:['PAS','IDEF'],paint:['FIN','REB']};boostKeys=keys[augment.id]||[];if(augment.id==='weakness'&&abilities.includes(augment.choice))boostKeys=[augment.choice];for(const key of boostKeys)r[key]=cap(r[key]+augment.tier*2/boostKeys.length,25,110);if(augment.id==='borrow'){const borrowed=(await talents()).find(t=>t.id===augment.choice);if(borrowed)for(const[k,v]of Object.entries(borrowed.boosts))r[k]=cap(r[k]+v,25,110);}}
 function gameRatings(home,playoff){const rr={...r};if(augment?.id==='home-away'){const key=home===team?'MID':'threePT';rr[key]=cap(rr[key]+augment.tier*2,25,110);}if(augment?.id==='postseason'){const key=playoff?'FIN':'threePT';rr[key]=cap(rr[key]+augment.tier*2,25,110);}if(augment?.id==='wildcard'){const key=['threePT','MID','FIN'][Math.floor(rng()*3)];rr[key]=cap(rr[key]+augment.tier*2,25,110);}if(augment?.id==='ageless')for(const k of ['ATH','DNK'])rr[k]=cap(rr[k]+Math.max(0,(d.career_context?.age||20)-34)*augment.tier*.3,25,110);return rr;}

 const roster={};for(const t of p.teams)roster[t[0]]=p.players.filter(x=>x[2]===t[0]).map(x=>({...candidate(x,season,p),composite:false,starter:x[11]>=25,tov:2,stl:x[9],blk:x[10],ratings:ratings(x)}));roster[team]=roster[canon(team)]||[];
 const strength=roster[team].slice(0,8).reduce((s,x)=>s+x.overall,0)/8;
 const winRate=cap(.48+(strength-72)*.013+(o-72)*.009+Number(d.reward_context?.trade_deadline?.team_strength_delta||0)*.05,.15,.85);
 const games=[];for(let i=0;i<82;i++){const opponent=p.teams[(i*7+Math.floor(rng()*29))%p.teams.length][0];const other=opponent===canon(team)?p.teams[(i+1)%p.teams.length][0]:opponent;const won=rng()<winRate,home=i%2?other:team,away=i%2?team:other,winScore=Math.round(104+rng()*28),loseScore=winScore-Math.round(1+rng()*16),l=line(gameRatings(home,false),rng);if(augment?.id==='endurance')l.min=cap(l.min+augment.tier*2,0,48);games.push({game:i+1,home,away,winner:won?team:other,home_score:home===(won?team:other)?winScore:loseScore,away_score:away===(won?team:other)?winScore:loseScore,player_line:l,box_score:{[team]:[{player:'我',player_id:-1,position:player.position,composite:true,starter:true,...l},...roster[team].slice(0,8)],[other]:(roster[other]||[]).slice(0,9)},overtime:0,narrative:won?'球队把握住关键回合，拿下胜利。':'最后的追分没能逆转，下一场继续。',events:[],clutch_events:[],date:`${season}:${i+1}`});}
 const wins=games.filter(g=>g.winner===team).length,seed=cap(Math.round((65-wins)/3)+1,1,15),made=seed<=8;
 const averages={games:82};for(const k of ['pts','reb','ast','stl','blk','tov','min','fgm','fga','three_made','three_attempts','ftm','fta'])averages[k]=Math.round(games.reduce((s,g)=>s+g.player_line[k],0)/82*10)/10;Object.assign(averages,{fg_pct:averages.fgm/averages.fga,three_pct:.36,ft_pct:.8});
 const rows=Object.values(roster).flat(),entries=rows.filter(x=>x.min>25).sort((a,b)=>b.pts-a.pts).map(c=>honor(c,c)),user=honor({player:'我',player_id:-1,team,position:player.position},averages,true);
 const pick=(yes,idx=0)=>yes?user:entries[idx]||user;const top=entries.slice(0,15);if(o>=82)top[0]=user;
 const honors={mvp:pick(o>=93&&wins>=55),scoring_champion:pick(averages.pts>30),dpoy:pick((r.PDEF+r.IDEF)/2>=94,1),roy:pick((d.career_context?.career_year||1)===1&&o>=80,2),sixth_man:pick(false,3),all_nba:{first:top.slice(0,5),second:top.slice(5,10),third:top.slice(10,15)},all_defense:{first:entries.slice(5,10),second:entries.slice(10,15)},all_star:{selected:o>=80?[user,...entries.slice(0,23)]:entries.slice(0,24)}};
 const series=[];let survived=made;for(const round of ['R1','WCSF','WCF','Finals']){if(!survived)break;const opponent=p.teams.filter(t=>canon(t[0])!==canon(team))[Math.floor(rng()*(p.teams.length-1))][0];let a=0,b=0,sg=[];while(a<4&&b<4){const won=rng()<cap(winRate-.04,.2,.78),home=sg.length%2?opponent:team,away=sg.length%2?team:opponent,l=line(gameRatings(home,true),rng),hi=Math.round(100+rng()*28),lo=hi-Math.round(1+rng()*14);won?a++:b++;sg.push({game:sg.length+1,round,home,away,winner:won?team:opponent,home_score:home===(won?team:opponent)?hi:lo,away_score:away===(won?team:opponent)?hi:lo,player_line:l,box_score:{[team]:[{player:'我',player_id:-1,position:player.position,starter:true,composite:true,...l},...roster[team].slice(0,8)],[opponent]:(roster[opponent]||[]).slice(0,9)},events:[],clutch_events:[]});}survived=a===4;series.push({round,teams:[team,opponent],winner:survived?team:opponent,games:sg,series:{[team]:a,[opponent]:b},locked_before_entry:{[team]:0,[opponent]:0}});}
 const champion=survived?team:series.at(-1)?.winner||p.teams[Math.floor(rng()*p.teams.length)][0];const standings={East:[],West:[]};for(const t of p.teams){const w=t[0]===canon(team)?wins:Math.round(24+rng()*40),row={team:t[0],team_id:t[1],wins:w,losses:82-w,win_pct:w/82,seed:1};(p.teams.indexOf(t)<15?standings.East:standings.West).push(row);}for(const a of Object.values(standings))a.sort((a,b)=>b.wins-a.wins).forEach((x,i)=>x.seed=i+1);
 const result={mode:'season',season,source_season:d.season,team,team_id:p.teams.find(x=>x[0]===canon(team))?.[1],seed:d.seed,career_year:d.career_context?.career_year||1,data_mode:parseInt(season)>2025?'projected':'historical',player:{...player,ratings:baseRatings},roster_snapshot:roster,retiring_teammates:[],standings,regular_season:{record:{wins,losses:82-wins},conference_seed:seed,games,player_averages:averages,player_availability:{games:82,available_games:82,missed_games:0,injuries:[],notes:[]},player_role:{starter:true,role:'核心',minutes:averages.min},roster_simulation:{}},play_in_games:[],playoff_series:series,league_honors:honors,finals_mvp:survived?user:entries[0],outcome:{champion,won_title:survived,made_playoffs:made,history_changed:true},narrative:[],stories:[],team_strength:strength};
 if(augment){result.augment_result={version:1,id:augment.id,effects:boostKeys.map(ability=>({ability,delta:augment.tier*2/boostKeys.length})),boosts:augment.boosts||{},earned:augment.reaperChoice||null};if(augment.id==='reaper'&&series.some(s=>s.winner===team)){const skills=await talents();result.augment_result.opportunity={round:series.find(s=>s.winner===team).round,options:skills.slice(0,3).map(s=>s.id)};}}const bf=d.career_context?.butterfly;if(bf)result.butterfly={...bf,version:1,stats_version:1,year:parseInt(season),token:bf.token||'local-league',echoes:[],closing_echoes:[]};return result;
 }
 window.parallelRequest=async(path,opts={})=>{const d=opts.data||{};if(path==='/team-offers')return draft(d);if(path==='/team-roster'){const p=await pack(d.season);return {roster:p.players.filter(x=>canon(x[2])===canon(d.team)).map(x=>candidate(x,d.season,p))};}if(path==='/simulate')return simulate(d);if(path==='/seasons')return {seasons:window.__REGRET_STATIC__.seasons};if(path==='/career/augment-options'){const p=await pack(d.season),skills=await talents();const matches=(s,r)=>s.playerId===Number(r[0])||s.mentor===r[1]||s.aliases.some(a=>a.replace(/[^a-z]/gi,'').toLowerCase()===r[1].replace(/[^a-z]/gi,'').toLowerCase());return {version:1,available:skills.filter(s=>p.players.some(r=>matches(s,r))).map(s=>s.id),teammates:skills.filter(s=>p.players.some(r=>canon(r[2])===canon(d.team)&&matches(s,r))).map(s=>s.id)};}if(path==='/career/develop'){const ratings={...d.player.ratings},before=avg(ratings),age=d.age||20,changes=[];if(age>=31)for(const k of abilities){const delta=['ATH','DNK','STR'].includes(k)?-2:-1;changes.push({ability:k,from:ratings[k],to:cap(ratings[k]+delta),delta});ratings[k]=cap(ratings[k]+delta);}return {ratings,potentials:Object.fromEntries(abilities.map(k=>[k,99])),age_before:age,age_after:age+1,overall_before:before,overall_after:avg(ratings),growth_points:age<27?6:age<32?3:1,changes,reason:'训练与年龄共同影响本季成长'};}if(path==='/career/next-season'){const y=parseInt(d.season)+1;return {season:y+'-'+String((y+1)%100).padStart(2,'0'),source_season:y>2025?'2025-26':y+'-'+String((y+1)%100).padStart(2,'0'),team:d.team,franchise_id:canon(d.team),projected:y>2025,projection_year:Math.max(0,y-2025)};}if(path==='/career/offers'){const p=await pack(d.season),rng=random(d.seed||1),teams=[p.teams.find(x=>x[0]===canon(d.team)),...p.teams.slice().sort(()=>rng()-.5).slice(0,3)].filter(Boolean);return {offers:teams.map((t,i)=>({id:'local-'+t[0]+'-'+d.seed,team:t[0],franchise_id:canon(t[0]),role:'核心轮换',kind:i?'contender':'stay',annual_salary_millions:Math.round((d.player.overall||75)*.3),reason:i?'球队希望与你一起争夺冠军':'球队希望你继续带队',team_record:{wins:45,losses:37},years:3})),butterfly:d.butterfly?{...d.butterfly,version:1,year:parseInt(d.season)+1}:undefined};}if(path.includes('save'))return null;if(path.includes('ranking')||path.includes('leaderboard'))return {entries:[],rows:[],total:0,page:1};throw Error('暂未支持的本地流程：'+path);};
 const noop=()=>{};
 window.ColorboxAI={configure:noop,track:noop,log:noop,event:noop,auth:{getUserInfo:async()=>null},storage:null,cloud:{auth:async()=>({code:200}),request:async({url,data,method})=>({code:200,statusCode:200,data:await window.parallelRequest(new URL(url,location.href).pathname,{data,method})})},navigateTo:noop,request:{},security:{checkAudit:async()=>({code:200})}};
 window.VaFuSDK={isInApp:true,getIsLogin:async()=>false,getUserInfo:async()=>null,track:noop,completeRewardVideoTask:async()=>({ok:true}),getActivityTaskState:async()=>({ok:true,state:{tasks:[{status:'pending',action:{kind:'reward_video'}}]}})};
 function notice(title){let d=document.getElementById('parallel-disabled');if(!d){d=document.createElement('dialog');d.id='parallel-disabled';d.style.cssText='max-width:320px;border:1px solid #d7cfc2;border-radius:18px;background:#faf7f0;padding:24px;color:#25251f;box-shadow:0 20px 80px #0004;font-family:inherit';d.innerHTML='<h3></h3><p>此模式仅保留入口，未制作内部内容。</p><button style="padding:10px 25px;border:0;border-radius:10px;background:#263f37;color:white">返回游戏</button>';d.querySelector('button').onclick=()=>d.close();document.body.append(d);}d.querySelector('h3').textContent=title;d.showModal();}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-star-cards-open],button');if(!b)return;const a=b.dataset.action||'';let title;if(b.matches('[data-star-cards-open]'))title='我的梦之队';if(['choose-regret','resume-home-regret'].includes(a))title='回到一场球';if(/trinity/.test(a)&&/^(start|resume|open)/.test(a))title='他化自在';if(title){e.preventDefault();e.stopImmediatePropagation();notice(title);}},true);
 // Preserve image-based rendering even when an upstream spelling has changed.
 let mapping;window.parallelAssetMap=fetch(BASE+'asset-manifest.json').then(r=>r.json()).then(m=>mapping=m.files);
 const remap=root=>{for(const img of root.querySelectorAll?.('img[src]')||[]){if(mapping?.[img.getAttribute('src')])img.src=mapping[img.getAttribute('src')];img.decoding='async';}};
 document.addEventListener('DOMContentLoaded',()=>{window.parallelAssetMap.then(()=>remap(document));new MutationObserver(rs=>{for(const r of rs)for(const n of r.addedNodes)if(n.nodeType===1)remap(n);}).observe(document.body,{childList:true,subtree:true});});
})();
